# Setup
title:            addbel0
description:      'This blog contain my writeup for CTF and Bug Bounty'
url:              /
baseurl:          /
theme:            jekyll-theme-minimal

paginate:         5