# Setup
title:            addbel0
description:      'Writeup for Bug Bounty and CTF'
url:              https://addbel0.github.io
baseurl:          /
theme:            jekyll-theme-minimal
logo :            /img/address_below0.png

paginate:         5
toc:              true